In [3]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np
import math

def FitSumResult(xT, yT):
  graphPos = []
  for i in range(yT):
    graphPos.append(sum(xT[i]), yT[i])

def TestKNN(xI, xT):
  output = []
  for input in xI: #cada input
    distance = [] #Guarda as distancias distancia
    for i in range(len(xT)): #cada referencia do treino
      vecSubtracted = SubtractVector(xT[i], input)
      distanceMag = GetVecMag(vecSubtracted) #Calcula a magnitude do vetor
      distance.append(distanceMag)
    output.append(distance)
  return output
  

def GetFinalY(result, yT):
  output = []
  for indexList in result:
    freq = []
    for neigh in indexList:
      freq.append(yT[neigh])
    output.append(MostFrequent(freq))
  return output

def GetFinalYWithWeights(result, distances, yT):
  output = []
  for indexList in range(len(result)):
    kResult_vDistance = {}
    for neigh in result[indexList]:
      AttOrAddToDic(kResult_vDistance, yT[neigh], CalculateWeight(distanceResult[indexList][neigh]))
    output.append(kResult_vDistance)
  return np.array(output)

def AttOrAddToDic(dic, key, value):
  if key in dic:
    dic[key] = dic[key] + value
  else: dic[key] = value

def MostFrequent(List):
  return max(set(List), key = List.count)

def SubtractVector(x, y):
  actualList = [] #Guarda o valor da subtração dos axis do vetor de n dimensões
  for val1, val2 in zip(x, y):
    actualList.append(val1 - val2)
  return actualList

def GetVecMag(vec):
  result = 0
  for axis in vec:
    result += axis**2
  result = math.sqrt(result)
  return result

def GetClosest(inputList, inputValue):
  arr = np.asarray(inputList)
  i = (np.abs(arr - inputValue)).argmin()

def CalculateAcc(result, yI):
  output = 0
  for i in range(len(result)):
    if(result[i] == yI[i]):
      output += 1
  output /= len(yI)
  return output

def GetLowestNValues(distances, k):
  output = []
  for result in distances:
    indexResult = []
    lowest = sorted(result)[:k]
    for value in lowest:
      indexResult.append(result.index(value))
    output.append(indexResult)
    
  return output

def CalculateWeight(distance):
  return 1/distance**2

def GetResultFromWeights(weightedResults):
  output = []
  for result in weightedResults:
    output.append(max(result, key=result.get))
  return output

def CreateConfusionMatrix(possibleResults):
  output = []
  for i in range(len(possibleResults)):
    line = []
    for j in range(len(possibleResults)):
      line.append(0)
    output.append(line)
  return output

def GetConfusionMatrix(result, trueBatch, confusionMatrix):
  for i in range(len(result)):
    confusionMatrix[result[i]][trueBatch[i]] += 1

def GetAllPossibleResults(yInput):
  output = []
  for result in yInput:
    output.append(result)
  output = list(set(output))
  return output

def NormalizeInput(x, normalizeValue):
  output = []
  x = x/normalizeValue
  return x
    

x, y = load_digits(return_X_y=True)
x = NormalizeInput(x, 16)
xTrain, xInput, yTrain, yInput = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)
k = 5

distanceResult = TestKNN(xInput, xTrain)
#print("Distances: ")
#print(np.matrix(distanceResult))
indexResult = GetLowestNValues(distanceResult, k)
#print("Indices: ")
#print(np.matrix(indexResult))
weightedResults = GetFinalYWithWeights(indexResult, distanceResult, yTrain)
#print("Weight Results:")
#print(np.matrix(weightedResults))
possibleResults = GetAllPossibleResults(yInput)
#print("Possible results:")
#print(possibleResults)
result = GetResultFromWeights(weightedResults)
#print("Result: ")
#print(np.matrix(result))
#print("Expected Result:")
#print(yInput)
confusionMatrix = CreateConfusionMatrix(possibleResults)
GetConfusionMatrix(result, yInput, confusionMatrix)
print(np.matrix(confusionMatrix))

accuracy = CalculateAcc(result, yInput)
formatAcc = "{:.1f}".format(accuracy*100)
print("Precisão: " + formatAcc + "%")

[[54  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  2  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  1  0]
 [ 0  0  0  0 54  0  0  0  0  1]
 [ 0  0  0  0  0 54  0  0  0  0]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0  0 54  1  0]
 [ 0  0  0  0  0  0  0  0 48  1]
 [ 0  0  0  0  0  1  0  0  0 52]]
Precisão: 98.7%
